---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-global
  namespace: mod-om-dev
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-global
  data:
    - secretKey: private-key
      remoteRef:
        key: secret-global
        property: private-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discount-management-secret
  namespace: mod-om-dev
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: discount-management-secret
  dataFrom:
    - extract:
        key: develop/mod-om/discount-management

