---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-p-secret
  namespace: mod-am-staging
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-p-secret
  dataFrom:
    - extract:
        key: staging/mod-am/test-p

