---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discount-management-secret
  namespace: mod-om-staging
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: discount-management-secret
  dataFrom:
    - extract:
        key: staging/mod-om/discount-management

