deployment:
  name: test-p
  image: asia-southeast1-docker.pkg.dev/myorder-beta/kubernetes/mod-am/test-p
  tag: init
  dep:
    - deployment:
        subName: ""
        namespace: mod-am-dev
        replicas: 1
        nodeSelector: 
          pool: regular
        resource:
          cpuRequest: 25m
          memoryRequest: 150Mi
          memoryLimit: 150Mi
        port: 8080
        hpa:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
      priorityClassName: tier-3
      labels:
        team: devops
      liveness:
        isEnabled: true
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        isEnabled: true
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 3
      volumes:
        GCLOUD:
          name: gcp-mod-am-svc
          mountPath: /etc/credentials-gcp
          secretName: gcp-mod-am-svc
      extraEnv:
        APP_ENV: develop
        GOOGLE_APPLICATION_CREDENTIALS: /etc/credentials/gcp-mod-am-svc.json
        TEST: 1235
        LOG_LEVEL: debug
        TEST12: 5555
